name: Google Cloud OIDC認証
description: Workload Identity連携を使用してGoogle Cloudに認証します

inputs:
  workload_identity_provider:
    description: Workload Identity ProviderのリソースID (省略時は環境変数 WORKLOAD_IDENTITY_PROVIDER を使用)
    required: false
    default: ""
  service_account:
    description: サービスアカウントのメールアドレス (省略時は環境変数 SERVICE_ACCOUNT を使用)
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: 認証情報の設定
      shell: bash
      run: |
        WIP="${{ inputs.workload_identity_provider }}"
        SA="${{ inputs.service_account }}"

        # 環境変数から取得
        [ -z "$WIP" ] && WIP="${WORKLOAD_IDENTITY_PROVIDER:-}"
        [ -z "$SA" ] && SA="${SERVICE_ACCOUNT:-}"

        # 必須チェック
        if [ -z "$WIP" ] || [ -z "$SA" ]; then
          echo "❌ エラー: 認証情報が設定されていません"
          exit 1
        fi

        # マスク
        echo "::add-mask::$WIP"
        echo "::add-mask::$SA"

        # 設定
        echo "WORKLOAD_IDENTITY_PROVIDER=$WIP" >> $GITHUB_ENV
        echo "SERVICE_ACCOUNT=$SA" >> $GITHUB_ENV

    - name: Google Cloud認証
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}
