name: Setup Go and Task
description: Common setup for Go and Task
inputs:
  go-version:
    description: "Go version to use"
    required: false
    default: "1.25.5"
  task-version:
    description: "Task version to use"
    required: false
    default: "3.46.4"
  working-directory:
    description: "Directory where go.sum is located"
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Set up Golang
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}
        cache-dependency-path: ${{ inputs.working-directory }}/go.sum

    - name: Install Task
      uses: go-task/setup-task@v1
      with:
        version: ${{ inputs.task-version }}
