name: Setup Terraform
description: Common setup for Terraform

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
      with:
        terraform_version: 1.14.4
        terraform_wrapper: false
