name: Setup Terraform
description: Common setup for Terraform

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.4
        terraform_wrapper: false
