name: Setup Terraform
description: Common setup for Terraform

inputs:
  terraform_wrapper:
    description: "Whether to enable the Terraform wrapper script"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.3
        terraform_wrapper: ${{ inputs.terraform_wrapper }}
